language: python
python:
- '3.6'
install: pip install -r requirements.txt -t .
script:
- true
after_success:
- mkdir dist
- find ./ -name '*.pyc' -delete
- zip -r dist/threatstack-to-aws-sns.zip . -x '.git/*' -x 'dist/*'
- cp deploy/cloudformation.json dist/threatstack-to-aws-sns.json
- sed -i.bak "s,%%SHA256%%,$(openssl dgst -binary -sha256 dist/threatstack-to-aws-sns.zip | openssl base64)," dist/threatstack-to-aws-sns.json
- ls -al dist
- cat dist/threatstack-to-aws-sns.json
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:
    secure: "ooyDo5BFY6wA/230JdlQlRJi3XeAxmJYhajfdOodxpv87tsEx2fFqL0p/QEGllvSRPKJqeYi6/lfrdxpFYgOOiN/ivsPOQZpBBoPUJoxEy5PC3oXJMRIgSQWF6J7FFPsq0NtdzsaKPZHrj1yBU/PSwrHzbTCwG0CqdPA82zOuZuvs92kNC3CZGJasQ8z09vZsZF4oFubVL9+OpPkMjGSv+HuajjgBlSk8pUrn7UH9snqFcqtEqLYvO8OnL7SP0yXim6xceOcUl7Tf4O0szu5djT+2aJytI4915U2EciYKn9M+MNmStSL1PMov1aE940ZUDXFf3rzxoWkP5aAQ3oPcVe6OPRP6EKgKGnYSMIlZnTbX51HTKpFgU9liQnt3k9CVJVmKQfL7k0iXNwlgdf4zgAPgJb5Ot6febi0f9P3+2U/Y82EvqCMOWYwk9CLc8BpYHg99Wwx11b6p8ekTvg0NVSoI0CsJrtoFQzzIIIJYxTQL0h3Rb/jatyq1cREqx8fXRJv3kF38fdM8CHjNVxaDMys2EzrowkvnGHoBTIo/V5XuwOSrph5/3N/Hya63vEv/Tn8fo71iJUlI7yd7O5Apax0uw4SlF1095gd87uhn+EcX426pRLlKe81EbbRMaUbS/X+HVsJoChwKCE2qnRKVvBYmmYg9ox+XZICkYHtm4s="
  secret_access_key:
    secure: "WQDqDyoQZr3xoPeGQHrkViMTxaoZZS70HHIO5KG08RfKFUU2FjIC/H2PJcraR0qBlHGmb+Q7KPYdUz3hq0T82x9js2GGNRagVQ52XBJFoV9fZypwkJj3TaL+65pfA0xmDHzHovqwFzEVoktpD3Dl2Rg0TSfD9bxLdXENb0EZCCVZ/grlkawkJ145yJ1cl6qlOSA7VTR1jEa3tJwt43NMSYkM0dMkoE3XaJ3bpcxOUH21GrHh0fbOj3CGL3kZWRuCCXMOIVWdbYE2ME+0aDUJb5Zi/NaZfhQRhV8tDe3NJVebPsX9NtemFOF1eODHSDBey7p5XjFEkRX4zU7iV/yiNzaFS5taMIv34YvCBxhOHE6Uhv+yv+sTYCf4zU5773EA/hyMVJg1onJlhoqy9rPKjkIHU70MxSrW0mUVVmzEWrEd7FzMyt8hBv1dFAyMWv4FHhaLr6rPDK4ptfL+vYq7pSIGYqN784RYVYD/HmWq5ixTW8qXUpfr9BT1Se/9YUCgiiYtJsmXQkEzCTv0XaCY/xgxlWarAec/+6NbJ20gY6Hp/H5qbLtFreZ2wt2Ffz278I5v9Hv8PbCTivwslA/OaVK7ln87BnXeRzAlukAux9NOVh3R5tp8yT162zcFyH6zEtxpzYgZ2UqDdLURA7YgEQ2o0OJjj0kEKHbfieW47w8="
  bucket: straycat-dhs-org-straycat-lambda-deploys
  local-dir: dist
  acl: public_read
  on:
    repo: tmclaugh/threatstack-to-aws-sns
